// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyDe3fQsSGKoD_nLJh7EyaWvjErB6Szg',
    appId: '1:895858274599:web:9344b6d581ad9dcef3b902',
    messagingSenderId: '895858274599',
    projectId: 'ecommerceapp-53119',
    authDomain: 'ecommerceapp-53119.firebaseapp.com',
    storageBucket: 'ecommerceapp-53119.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_rsv86KQTpTeYs5_ft-DBity_ULGLkU',
    appId: '1:895858274599:android:b417193985fc0a41f3b902',
    messagingSenderId: '895858274599',
    projectId: 'ecommerceapp-53119',
    storageBucket: 'ecommerceapp-53119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnNKdx0N4j0QqmFsORK4ETZ1JfNKw-ZQ',
    appId: '1:895858274599:ios:ba458be12a83f990f3b902',
    messagingSenderId: '895858274599',
    projectId: 'ecommerceapp-53119',
    storageBucket: 'ecommerceapp-53119.appspot.com',
    androidClientId: '895858274599-o4gaqtqu9o7is371vjedjl81ai6t3a7m.apps.googleusercontent.com',
    iosClientId: '895858274599-8b9n6qpv73vhpurfj8ernr3m4pt2etpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
